In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
iris = load_iris()

In [14]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(max_iter=200), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
cross_val_score(SVC(), iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [17]:
cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [18]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])